packages:
  - packages/*

catalog:
  '@types/node': 22.19.7
  typescript: 5.9.3
  publint: 0.3.17
  vite: 7.3.1
  vitest: 3.2.4
  vite-plugin-dts: 4.5.4
  rollup-plugin-node-externals: 8.1.2

onlyBuiltDependencies:
  - esbuild
