packages:
  - packages/*

catalog:
  '@types/node': 22.19.21
  typescript: 5.9.3
  publint: 0.3.21
  vite: 7.3.5
  vitest: 3.2.6
  vite-plugin-dts: 5.0.3
  rollup-plugin-node-externals: 8.1.2

onlyBuiltDependencies:
  - esbuild
