packages:
  - packages/*

catalog:
  '@types/node': 22.20.1
  typescript: 7.0.2
  publint: 0.3.21
  vite: 7.3.6
  vitest: 3.2.7
  vite-plugin-dts: 4.5.4
  rollup-plugin-node-externals: 8.1.2

onlyBuiltDependencies:
  - esbuild
