packages:
  - packages/*

catalog:
  '@types/node': 24.13.3
  typescript: 5.9.3
  publint: 0.3.21
  vite: 7.3.6
  vitest: 3.2.7
  vite-plugin-dts: 4.5.4
  rollup-plugin-node-externals: 8.1.2

onlyBuiltDependencies:
  - esbuild
